import * as fs from 'node:fs';
import * as path from 'node:path';

export const PLUGIN_ID = 'content-schemas';
export const PLUGIN_NAME = 'Content Schemas';
export const FILE_HEADER =
  '/* Auto-generated by strapi-plugin-content-schemas. Do not edit. */\n/* eslint-disable */';

// Bumped when the generated output layout/contract changes incompatibly;
// exposed in the manifest so the CLI can detect server/CLI mismatches
export const SCHEMA_FORMAT_VERSION = 1;

// Name of the generated upload-file schema export (shared/upload-file.ts);
// every emitter that references media must agree on it
export const UPLOAD_FILE_SCHEMA_NAME = 'UploadFileSchema';

// Works from both source (server/src/constants) and bundled output (dist/server) -
// walks up until it finds this plugin's own package.json
const findPluginVersion = (): string => {
  let dir = __dirname;
  for (let i = 0; i < 6; i++) {
    const pkgPath = path.join(dir, 'package.json');
    if (fs.existsSync(pkgPath)) {
      try {
        const pkg = JSON.parse(fs.readFileSync(pkgPath, 'utf-8')) as {
          name?: string;
          version?: string;
        };
        if (pkg.name === 'strapi-plugin-content-schemas' && pkg.version) return pkg.version;
      } catch {
        // unreadable package.json - keep walking up
      }
    }
    const parent = path.dirname(dir);
    if (parent === dir) break;
    dir = parent;
  }
  return '0.0.0';
};

export const PLUGIN_VERSION = findPluginVersion();
