import { describe, it, expect, beforeAll } from 'vitest';
import fs from 'node:fs';
import path from 'node:path';

import { GENERATED_DIR } from './helpers/generated-dir';

const readGenerated = (relPath: string): string =>
  fs.readFileSync(path.join(GENERATED_DIR, relPath), 'utf-8');

describe('shared/upload-file.ts', () => {
  let content: string;
  beforeAll(() => {
    content = readGenerated('shared/upload-file.ts');
  });

  it('exports UploadFileSchema', () => {
    expect(content).toContain('export const UploadFileSchema = object({');
  });

  it('exports UploadFile type', () => {
    expect(content).toContain('export type UploadFile = InferInput<typeof UploadFileSchema>;');
  });

  it('has url and mime fields', () => {
    expect(content).toContain('url: string()');
    expect(content).toContain('mime: string()');
  });

  it('has the extended v5 media fields', () => {
    expect(content).toContain('documentId: string()');
    expect(content).toContain('hash: string()');
    expect(content).toContain('previewUrl: nullish(string())');
    expect(content).toContain('provider: string()');
  });

  it('has typed formats via UploadFileFormatSchema', () => {
    expect(content).toContain('export const UploadFileFormatSchema = object({');
    expect(content).toContain('formats: nullish(record(string(), UploadFileFormatSchema))');
  });
});

describe('shared/overrides.ts', () => {
  let content: string;
  beforeAll(() => {
    content = readGenerated('shared/overrides.ts');
  });

  it('exports RenderedHtmlSchema', () => {
    expect(content).toContain('export const RenderedHtmlSchema');
  });

  it('exports RenderedHtml type', () => {
    expect(content).toContain('export type RenderedHtml = InferInput<typeof RenderedHtmlSchema>;');
  });
});

describe('richtext override applied across content types and components', () => {
  it('article.content uses RenderedHtmlSchema (required richtext)', () => {
    const content = readGenerated('content-types/article.ts');
    expect(content).toContain('content: RenderedHtmlSchema');
  });

  it('footer richtext fields use RenderedHtmlSchema', () => {
    const content = readGenerated('content-types/footer.ts');
    expect(content).toContain('subtitle: nullish(RenderedHtmlSchema)');
    expect(content).toContain('bottomText: nullish(RenderedHtmlSchema)');
  });

  it('hero-section richtext fields use RenderedHtmlSchema', () => {
    const content = readGenerated('components/modules/hero-section.ts');
    expect(content).toContain('title: RenderedHtmlSchema');
    expect(content).toContain('subtitle: nullish(RenderedHtmlSchema)');
  });

  it('faq-item.answer uses RenderedHtmlSchema', () => {
    const content = readGenerated('components/modules/faq-item.ts');
    expect(content).toContain('answer: RenderedHtmlSchema');
  });

  it('content-block.content uses RenderedHtmlSchema', () => {
    const content = readGenerated('components/modules/content-block.ts');
    expect(content).toContain('content: RenderedHtmlSchema');
  });
});

describe('file headers', () => {
  it('all generated files have the configured header', () => {
    const files = [
      'content-types/article.ts',
      'shared/upload-file.ts',
      'shared/overrides.ts',
      'index.ts',
    ];
    for (const file of files) {
      const content = readGenerated(file);
      expect(content).toContain('Auto-generated by strapi-plugin-content-schemas');
    }
  });
});
