import { describe, it, expect } from 'vitest';
import * as fs from 'node:fs';
import * as path from 'node:path';

// Generated by the e2e globalSetup via `strapi-schemas pull` against the app
// that runs BOTH plugins - exercises the per-view schema generation end to end.
const APP_DIR = path.resolve(__dirname, 'strapi-app');
const VALIBOT_DIR = path.resolve(APP_DIR, '.tmp', 'generated-valibot');
const ZOD_DIR = path.resolve(APP_DIR, '.tmp', 'generated-zod');

const read = (dir: string, relPath: string): string =>
  fs.readFileSync(path.join(dir, relPath), 'utf-8');

describe('per-view schemas (valibot)', () => {
  it('generates a views folder with schemas, barrel, envelope, and manifest', () => {
    expect(fs.existsSync(path.join(VALIBOT_DIR, 'views'))).toBe(true);
    for (const file of [
      'page-view.ts',
      'product-view.ts',
      'index.ts',
      'envelope.ts',
      'manifest.json',
    ]) {
      expect(fs.existsSync(path.join(VALIBOT_DIR, 'views', file))).toBe(true);
    }
  });

  it('emits an exact response schema for the hook-free view', () => {
    const content = read(VALIBOT_DIR, 'views/page-view.ts');

    expect(content).toContain('export const PageViewDataSchema = object({');
    // entity-level objects promise the runtime-guaranteed row id
    expect(content).toContain('export const PageViewDataSchema = object({\n  id: number(),');
    expect(content).toContain('  title: string(),');
    expect(content).toContain('  slug: string(),');
    expect(content).toContain('  seo: nullish(SharedSeoSchema),');
    // dual-use components fall back from variant() to union(); prettier may
    // wrap the expression - accept both forms across lines
    expect(content).toMatch(/modules: array\(\s*(variant\(\s*'__component',\s*|union\(\s*)\[/);
    expect(content).toContain("looseObject({ view: literal('page-view') })");
    // richtext transform is covered by the app's typeOverrides → no warnings
    expect(content).not.toContain('GENERATOR WARNINGS');
  });

  it('emits an exact view-local slice for the planner.components override', () => {
    const content = read(VALIBOT_DIR, 'views/page-view.ts');

    // modules.product-grid is narrowed by the override → named slice with a
    // required discriminator, used inside the zone union
    expect(content).toContain('export const PageViewModulesProductGridSliceSchema = object({');
    expect(content).toContain("__component: literal('modules.product-grid')");
    expect(content).toContain('PageViewModulesProductGridSliceSchema,');

    // relation narrowed by fields + nested media populate
    expect(content).toContain('documentId: string(),');
    expect(content).toContain('sku: string(),');
    expect(content).toContain('thumbnail: nullish(UploadFileSchema),');

    // promoTiles populated with `true` → scalars-only inline slice, no shared
    // schema import
    expect(content).toContain('link: string(),');
    expect(content).not.toContain('ModulesPromoTileSchema');

    // prettier may wrap the long type alias across lines
    expect(content).toMatch(
      /export type PageViewModulesProductGridSlice = InferOutput<\s*typeof PageViewModulesProductGridSliceSchema\s*>;/,
    );
  });

  it('emits only a merged schema for the assemble view, with relation narrowing', () => {
    const content = read(VALIBOT_DIR, 'views/product-view.ts');

    expect(content).toContain('export const ProductViewMergedSchema = object({');
    expect(content).not.toContain('ProductViewResponseSchema');
    expect(content).toContain('    variantName: string(),');
    expect(content).toContain('  images: nullish(array(UploadFileSchema)),');
    expect(content).toContain('  thumbnail: nullish(UploadFileSchema),');
    // relation slices carry id (runtime always returns it) and support
    // timestamp field selections despite their IR exclusion
    expect(content).toContain('    id: number(),');
    expect(content).toContain('    updatedAt: nullish(string()),');
  });

  it('emits the declared response schema for the assemble view with wrappers', () => {
    const content = read(VALIBOT_DIR, 'views/product-view.ts');

    expect(content).toContain(
      'export const ProductViewAssembledSchema = object({ product: ProductViewMergedSchema });',
    );
    expect(content).toMatch(
      /export type ProductViewAssembled = InferOutput<\s*typeof ProductViewAssembledSchema\s*>;/,
    );
    expect(content).toContain('export const ProductViewAssembledSuccessSchema = object({');
    expect(content).toContain("meta: looseObject({ view: literal('product-view') })");
    expect(content).toMatch(
      /export const ProductViewAssembledResultSchema = union\(\[\s*ProductViewAssembledSuccessSchema,\s*BffErrorEnvelopeSchema,?\s*\]\);/,
    );
    expect(content).toContain("import { BffErrorEnvelopeSchema } from './envelope';");
  });

  it('generates singleton views like keyed views', () => {
    const content = read(VALIBOT_DIR, 'views/announcement-view.ts');

    expect(content).toContain('export const AnnouncementViewDataSchema = object({');
    expect(content).toContain('title: string(),');
    expect(content).toContain('export const AnnouncementViewResponseSchema = object({');
    expect(content).toContain("literal('announcement-view')");
  });

  it('generates composite views as an object of per-source shapes', () => {
    const content = read(VALIBOT_DIR, 'views/chrome.ts');

    // single-doc source: nullable; many source: full-list array
    expect(content).toMatch(/announcement: nullish\(\s*object\(\{/);
    expect(content).toMatch(/categories: array\(\s*object\(\{/);
    // per-source objects lead with the runtime-guaranteed row id
    expect(content).toMatch(/announcement: nullish\(\s*object\(\{\s*id: number\(\),/);
    expect(content).toMatch(/categories: array\(\s*object\(\{\s*id: number\(\),/);
    expect(content).toContain('icon: nullish(UploadFileSchema),');
    expect(content).toContain('export const ChromeResponseSchema = object({');
  });

  it('re-exports views from the root barrel', () => {
    expect(read(VALIBOT_DIR, 'index.ts')).toContain("export * from './views';");
  });

  it('ships the derivation manifest alongside the schemas', () => {
    const manifest = JSON.parse(read(VALIBOT_DIR, 'views/manifest.json'));

    expect(manifest.manifestVersion).toBe(1);
    const ids = manifest.views.map((view: { id: string }) => view.id);
    expect(ids).toEqual([
      'page-view',
      'article-view',
      'announcement-view',
      'chrome',
      'product-view',
    ]);
    const productView = manifest.views.find((view: { id: string }) => view.id === 'product-view');
    expect(productView.hasAssemble).toBe(true);
    const chrome = manifest.views.find((view: { id: string }) => view.id === 'chrome');
    expect(chrome.kind).toBe('composite');
  });
});

describe('per-view schemas (zod)', () => {
  it('emits the zod variant of the view schemas', () => {
    const content = read(ZOD_DIR, 'views/page-view.ts');

    expect(content).toContain('export const PageViewDataSchema = z.object({');
    expect(content).toContain("z.literal('page-view')");
    expect(content).toMatch(
      /modules: z\.array\(\s*z\.(discriminatedUnion\(\s*'__component',\s*|union\(\s*)\[/,
    );
  });

  it('emits the zod variant of the declared response schema', () => {
    const content = read(ZOD_DIR, 'views/product-view.ts');

    expect(content).toContain(
      'export const ProductViewAssembledSchema = z.object({ product: ProductViewMergedSchema });',
    );
    expect(content).toMatch(
      /export const ProductViewAssembledResultSchema = z\.union\(\[\s*ProductViewAssembledSuccessSchema,\s*BffErrorEnvelopeSchema,?\s*\]\);/,
    );
  });

  it('emits the zod variant of the override slice', () => {
    const content = read(ZOD_DIR, 'views/page-view.ts');

    expect(content).toContain('export const PageViewModulesProductGridSliceSchema = z.object({');
    expect(content).toContain("__component: z.literal('modules.product-grid')");
    expect(content).toMatch(
      /export type PageViewModulesProductGridSlice = z\.infer<\s*typeof PageViewModulesProductGridSliceSchema\s*>;/,
    );
  });
});
