// Single source of truth for valibot function detection in generated code.
// Used by both the primitives mapper (schema files) and the overrides builder -
// keeping one list prevents the two from drifting apart.
//
// The list is the full set of callable valibot v1 exports (minus bare reserved
// words like `enum`/`null`, which cannot appear in a named import - their `_`
// aliases are included instead). Override schemas can use any of them, so a
// partial list would generate files with missing imports.
export const VALIBOT_FUNCTIONS = [
  'any',
  'args',
  'array',
  'assert',
  'base64',
  'bic',
  'bigint',
  'blob',
  'boolean',
  'brand',
  'bytes',
  'check',
  'checkItems',
  'config',
  'creditCard',
  'cuid2',
  'custom',
  'date',
  'decimal',
  'description',
  'digits',
  'domain',
  'email',
  'emoji',
  'empty',
  'endsWith',
  'entries',
  'entriesFromList',
  'entriesFromObjects',
  'enum_',
  'everyItem',
  'exactOptional',
  'examples',
  'excludes',
  'fallback',
  'file',
  'filterItems',
  'findItem',
  'finite',
  'flatten',
  'forward',
  'function_',
  'getDefault',
  'getDefaults',
  'getFallback',
  'getFallbacks',
  'graphemes',
  'gtValue',
  'guard',
  'hash',
  'hexColor',
  'hexadecimal',
  'imei',
  'includes',
  'instance',
  'integer',
  'intersect',
  'ip',
  'ipv4',
  'ipv6',
  'is',
  'isbn',
  'isoDate',
  'isoDateTime',
  'isoDateTimeSecond',
  'isoTime',
  'isoTimeSecond',
  'isoTimestamp',
  'isoWeek',
  'isrc',
  'keyof',
  'lazy',
  'length',
  'literal',
  'looseObject',
  'looseTuple',
  'ltValue',
  'mac',
  'mac48',
  'mac64',
  'map',
  'mapItems',
  'maxBytes',
  'maxEntries',
  'maxGraphemes',
  'maxLength',
  'maxSize',
  'maxValue',
  'maxWords',
  'message',
  'metadata',
  'mimeType',
  'minBytes',
  'minEntries',
  'minGraphemes',
  'minLength',
  'minSize',
  'minValue',
  'minWords',
  'multipleOf',
  'nan',
  'nanoid',
  'never',
  'nonEmpty',
  'nonNullable',
  'nonNullish',
  'nonOptional',
  'normalize',
  'notBytes',
  'notEntries',
  'notGraphemes',
  'notLength',
  'notSize',
  'notValue',
  'notValues',
  'notWords',
  'null_',
  'nullable',
  'nullish',
  'number',
  'object',
  'objectWithRest',
  'octal',
  'omit',
  'optional',
  'parse',
  'parseBoolean',
  'parseJson',
  'parser',
  'partial',
  'partialCheck',
  'pick',
  'picklist',
  'pipe',
  'promise',
  'rawCheck',
  'rawTransform',
  'readonly',
  'record',
  'reduceItems',
  'regex',
  'required',
  'returns',
  'rfcEmail',
  'safeInteger',
  'safeParse',
  'safeParser',
  'set',
  'size',
  'slug',
  'someItem',
  'sortItems',
  'startsWith',
  'strictObject',
  'strictTuple',
  'string',
  'stringifyJson',
  'symbol',
  'title',
  'toBigint',
  'toBoolean',
  'toCamelCase',
  'toDate',
  'toKebabCase',
  'toLowerCase',
  'toMaxValue',
  'toMinValue',
  'toNumber',
  'toPascalCase',
  'toSnakeCase',
  'toString',
  'toUpperCase',
  'transform',
  'trim',
  'trimEnd',
  'trimStart',
  'tuple',
  'tupleWithRest',
  'ulid',
  'undefined_',
  'undefinedable',
  'union',
  'unknown',
  'unwrap',
  'url',
  'uuid',
  'value',
  'values',
  'variant',
  'void_',
  'words',
] as const;

export type ValibotFunction = (typeof VALIBOT_FUNCTIONS)[number];

// Match bare calls only: `pipe(` yes, `JSON.parse(` and `toNumber(` no -
// substring matching would drag in imports for method calls and suffix matches
const buildCallPattern = (fn: string): RegExp => new RegExp(`(?<![\\w$.])${fn}\\(`);

export const detectUsedFunctions = (code: string): ReadonlySet<string> => {
  const used = new Set<string>();
  for (const fn of VALIBOT_FUNCTIONS) {
    if (buildCallPattern(fn).test(code)) used.add(fn);
  }
  return used;
};
