import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import * as fs from 'node:fs';
import * as path from 'node:path';

import { check, diffFiles } from '../../../cli/src/check';
import { pull } from '../../../cli/src/pull';
import { META_FILE_NAME } from '../../../cli/src/constants';

vi.mock('../../../cli/src/pull', () => ({ pull: vi.fn() }));

const HEADER = '/* Auto-generated by strapi-plugin-content-schemas. Do not edit. */\n';

const generated = (body: string): string => `${HEADER}${body}`;

describe('diffFiles', () => {
  it('reports no changes for identical file sets', () => {
    const committed = new Map([['index.ts', generated('export {};')]]);
    const fresh = new Map([['index.ts', generated('export {};')]]);

    const result = diffFiles(committed, fresh);
    expect(result).toEqual({ added: [], removed: [], modified: [], ignored: [] });
  });

  it('reports fresh-only files as added and changed files as modified', () => {
    const committed = new Map([['a.ts', generated('old')]]);
    const fresh = new Map([
      ['a.ts', generated('new')],
      ['b.ts', generated('added')],
    ]);

    const result = diffFiles(committed, fresh);
    expect(result.added).toEqual(['b.ts']);
    expect(result.modified).toEqual(['a.ts']);
  });

  it('reports committed generated files missing from a fresh pull as removed', () => {
    const committed = new Map([['stale.ts', generated('gone content type')]]);
    const fresh = new Map<string, string>();

    const result = diffFiles(committed, fresh);
    expect(result.removed).toEqual(['stale.ts']);
    expect(result.ignored).toEqual([]);
  });

  it('ignores hand-added files without the generated header', () => {
    const committed = new Map([
      ['README.md', '# my notes'],
      ['.gitkeep', ''],
      ['index.ts', generated('export {};')],
    ]);
    const fresh = new Map([['index.ts', generated('export {};')]]);

    const result = diffFiles(committed, fresh);
    expect(result.removed).toEqual([]);
    expect(result.ignored).toEqual(['README.md', '.gitkeep']);
  });
});

describe('check', () => {
  const COMMITTED_DIR = path.join(__dirname, '.tmp-check-test');

  beforeEach(() => {
    fs.mkdirSync(COMMITTED_DIR, { recursive: true });
    vi.spyOn(console, 'log').mockImplementation(() => {});
    vi.spyOn(console, 'error').mockImplementation(() => {});
  });

  afterEach(() => {
    fs.rmSync(COMMITTED_DIR, { recursive: true, force: true });
    vi.restoreAllMocks();
  });

  const capturePullTempDir = (freshFiles: Record<string, string>): { tempDir: string } => {
    const captured = { tempDir: '' };
    vi.mocked(pull).mockImplementation(async (_url, _token, outputDir) => {
      captured.tempDir = outputDir;
      for (const [name, content] of Object.entries(freshFiles)) {
        fs.writeFileSync(path.join(outputDir, name), content);
      }
      return 'mock-hash';
    });
    return captured;
  };

  it('returns up-to-date and removes the temp dir when nothing changed', async () => {
    fs.writeFileSync(path.join(COMMITTED_DIR, 'index.ts'), generated('export {};'));
    const captured = capturePullTempDir({ 'index.ts': generated('export {};') });

    const result = await check(
      'http://localhost:1337',
      'token',
      COMMITTED_DIR,
      '',
      false,
      'valibot',
    );

    expect(result).toBe('up-to-date');
    expect(captured.tempDir).not.toBe('');
    expect(fs.existsSync(captured.tempDir)).toBe(false);
  });

  it('returns stale and still removes the temp dir', async () => {
    const captured = capturePullTempDir({ 'new.ts': generated('added') });

    const result = await check(
      'http://localhost:1337',
      'token',
      COMMITTED_DIR,
      '',
      false,
      'valibot',
    );

    expect(result).toBe('stale');
    expect(fs.existsSync(captured.tempDir)).toBe(false);
  });

  it('creates the candidate dir next to the output dir so prettier resolves the same config', async () => {
    fs.writeFileSync(path.join(COMMITTED_DIR, 'index.ts'), generated('export {};'));
    const captured = capturePullTempDir({ 'index.ts': generated('export {};') });

    await check('http://localhost:1337', 'token', COMMITTED_DIR, '', true, 'valibot');

    // Same directory tree as the committed output - prettier walks up from
    // each file's path, so both sides must resolve the consumer repo's config.
    expect(path.dirname(captured.tempDir)).toBe(path.dirname(COMMITTED_DIR));
    expect(path.basename(captured.tempDir)).toMatch(/^\.strapi-schemas-check-/);
  });

  it('ignores the meta file so a CLI upgrade alone is not reported as drift', async () => {
    fs.writeFileSync(path.join(COMMITTED_DIR, 'index.ts'), generated('export {};'));
    fs.writeFileSync(path.join(COMMITTED_DIR, META_FILE_NAME), '{ "cliVersion": "0.2.3" }');
    capturePullTempDir({
      'index.ts': generated('export {};'),
      [META_FILE_NAME]: '{ "cliVersion": "1.0.0" }',
    });

    const result = await check(
      'http://localhost:1337',
      'token',
      COMMITTED_DIR,
      '',
      false,
      'valibot',
    );

    expect(result).toBe('up-to-date');
  });

  it('creates the output parent directory when it does not exist yet', async () => {
    const nested = path.join(COMMITTED_DIR, 'missing-parent', 'generated');
    const captured = capturePullTempDir({ 'index.ts': generated('export {};') });

    const result = await check('http://localhost:1337', 'token', nested, '', false, 'valibot');

    expect(result).toBe('stale');
    expect(path.dirname(captured.tempDir)).toBe(path.dirname(nested));
  });

  it('removes the temp dir when pull rejects', async () => {
    const captured = { tempDir: '' };
    vi.mocked(pull).mockImplementation(async (_url, _token, outputDir) => {
      captured.tempDir = outputDir;
      throw new Error('network down');
    });

    await expect(
      check('http://localhost:1337', 'token', COMMITTED_DIR, '', false, 'valibot'),
    ).rejects.toThrow('network down');
    expect(fs.existsSync(captured.tempDir)).toBe(false);
  });
});
