import { describe, it, expect, beforeEach, afterEach, vi } from 'vitest';
import * as fs from 'node:fs';
import * as path from 'node:path';

import { pack } from '../../../cli/src/pack';
import { META_FILE_NAME } from '../../../cli/src/constants';

// A tiny "pulled" output using zod (installed at the plugin root, like
// typescript), so pack compiles it exactly as it would a real pull
const ROOT = path.join(__dirname, '.tmp-pack-test');
const SOURCE = path.join(ROOT, 'src');
const OUT = path.join(ROOT, 'out');

const HEADER = '/* Auto-generated by strapi-plugin-content-schemas. Do not edit. */\n';

const writeSource = (files: Record<string, string>, meta: Record<string, unknown>): void => {
  fs.rmSync(SOURCE, { recursive: true, force: true });
  for (const [name, content] of Object.entries(files)) {
    const file = path.join(SOURCE, name);
    fs.mkdirSync(path.dirname(file), { recursive: true });
    fs.writeFileSync(file, `${HEADER}${content}`);
  }
  fs.writeFileSync(path.join(SOURCE, META_FILE_NAME), `${JSON.stringify(meta, null, 2)}\n`);
};

const VALID_SOURCE = {
  'content-types/article.ts': [
    "import { z } from 'zod';",
    'export const ArticleSchema = z.object({ documentId: z.string(), title: z.string() });',
    'export type Article = z.infer<typeof ArticleSchema>;',
  ].join('\n'),
  'views/page.ts': "export const PAGE_VIEW = 'page' as const;",
  'views/index.ts': "export * from './page';",
  'index.ts': [
    "export { ArticleSchema, type Article } from './content-types/article';",
    "export * from './views';",
  ].join('\n'),
};

const VALID_META = {
  hash: 'f'.repeat(64),
  target: 'zod',
  files: ['content-types/article.ts', 'index.ts', 'views/index.ts', 'views/page.ts'],
  cliVersion: '0.0.0',
};

const packOptions = {
  url: 'http://unused',
  token: 'unused',
  query: '',
  target: 'zod',
  name: '@acme/contracts',
  version: '2.0.0',
  out: path.relative(process.cwd(), OUT),
  from: path.relative(process.cwd(), SOURCE),
};

const snapshot = (dir: string): Map<string, string> => {
  const files = new Map<string, string>();
  const walk = (current: string): void => {
    for (const entry of fs.readdirSync(current, { withFileTypes: true })) {
      const full = path.join(current, entry.name);
      if (entry.isDirectory()) walk(full);
      else files.set(path.relative(dir, full), fs.readFileSync(full, 'utf-8'));
    }
  };
  walk(dir);
  return files;
};

describe('pack', () => {
  beforeEach(() => {
    fs.mkdirSync(ROOT, { recursive: true });
    vi.spyOn(console, 'log').mockImplementation(() => {});
  });

  afterEach(() => {
    fs.rmSync(ROOT, { recursive: true, force: true });
    vi.restoreAllMocks();
  });

  it('compiles both formats with declarations, a types-only entry and a manifest', async () => {
    writeSource(VALID_SOURCE, VALID_META);

    const hash = await pack(packOptions);

    expect(hash).toBe(VALID_META.hash);
    const files = snapshot(OUT);
    for (const expected of [
      'package.json',
      'dist/esm/package.json',
      'dist/esm/index.js',
      'dist/esm/index.d.ts',
      'dist/esm/types.js',
      'dist/esm/types.d.ts',
      'dist/esm/content-types/article.js',
      'dist/esm/views/index.js',
      'dist/cjs/package.json',
      'dist/cjs/index.js',
      'dist/cjs/index.d.ts',
      'dist/cjs/types.d.ts',
    ]) {
      expect(files.has(expected), expected).toBe(true);
    }
    expect(JSON.parse(files.get('dist/esm/package.json') ?? '{}')).toEqual({ type: 'module' });
    expect(JSON.parse(files.get('dist/cjs/package.json') ?? '{}')).toEqual({ type: 'commonjs' });
    // the types entry carries no runtime code
    expect(files.get('dist/esm/types.js')?.trim()).toBe('export {};');
    expect(files.get('dist/esm/types.d.ts')).toContain("export type * from './index.js';");
  });

  it('rewrites relative specifiers in the ESM build only', async () => {
    writeSource(VALID_SOURCE, VALID_META);

    await pack(packOptions);

    const esmIndex = fs.readFileSync(path.join(OUT, 'dist/esm/index.js'), 'utf-8');
    const esmTypes = fs.readFileSync(path.join(OUT, 'dist/esm/index.d.ts'), 'utf-8');
    const cjsIndex = fs.readFileSync(path.join(OUT, 'dist/cjs/index.js'), 'utf-8');
    expect(esmIndex).toContain("from './content-types/article.js'");
    expect(esmIndex).toContain("from './views/index.js'");
    expect(esmTypes).toContain("from './content-types/article.js'");
    expect(cjsIndex).toContain('require("./content-types/article")');
    expect(cjsIndex).not.toContain('.js")');
  });

  it('writes the package manifest from flags, meta and the installed schema library', async () => {
    writeSource(VALID_SOURCE, VALID_META);

    await pack(packOptions);

    const manifest = JSON.parse(fs.readFileSync(path.join(OUT, 'package.json'), 'utf-8'));
    expect(manifest.name).toBe('@acme/contracts');
    expect(manifest.version).toBe('2.0.0');
    expect(manifest.peerDependencies.zod).toMatch(/^\^\d+\.\d+\.\d+/);
    expect(manifest.contentSchemas.hash).toBe(VALID_META.hash);
    expect(manifest.contentSchemas.target).toBe('zod');
    expect(manifest.exports['./mocks']).toBeUndefined();
  });

  it('is byte-identical across runs and leaves the source directory untouched', async () => {
    writeSource(VALID_SOURCE, VALID_META);
    const sourceBefore = snapshot(SOURCE);

    await pack(packOptions);
    const first = snapshot(OUT);
    await pack(packOptions);
    const second = snapshot(OUT);

    expect(second).toEqual(first);
    expect(snapshot(SOURCE)).toEqual(sourceBefore);
    expect(fs.readdirSync(ROOT).filter((n) => n.startsWith('.strapi-schemas-pack-src-'))).toEqual(
      [],
    );
  });

  it('fails with the compiler diagnostics when the output does not compile', async () => {
    writeSource(
      { ...VALID_SOURCE, 'index.ts': "export const broken: number = 'nope';" },
      VALID_META,
    );

    await expect(pack(packOptions)).rejects.toThrow(/index\.ts:\d+:\d+ .*not assignable/);
  });

  it('refuses a --from directory that pull did not write', async () => {
    fs.rmSync(SOURCE, { recursive: true, force: true });
    fs.mkdirSync(SOURCE, { recursive: true });

    await expect(pack(packOptions)).rejects.toThrow(/has no \.strapi-schemas-meta\.json/);
  });

  it('refuses the project root as --out', async () => {
    writeSource(VALID_SOURCE, VALID_META);

    await expect(pack({ ...packOptions, out: '.' })).rejects.toThrow(/dedicated directory/);
  });
});
