export const GENERATED_MARKER = 'Auto-generated by strapi-plugin-content-schemas';

export const REQUEST_TIMEOUT_MS = 30_000;

// Generated output for even very large content models is a few MB; these caps
// only exist so a hostile or broken server cannot exhaust memory
export const MAX_RESPONSE_BYTES = 64 * 1024 * 1024;
export const MAX_TARBALL_BYTES = 256 * 1024 * 1024;

// Written into the output dir on every pull so the artifact is self-describing
// (dev servers read it for a mode line; `pack` will read it to embed the hash)
export const META_FILE_NAME = '.strapi-schemas-meta.json';

export const DEFAULT_WATCH_INTERVAL_MS = 3000;

// The token is secret: the environment keeps it out of shell history and
// process listings, which `--token` cannot
export const TOKEN_ENV_VAR = 'STRAPI_SCHEMAS_TOKEN';

// CI distinguishes "schemas are stale" from "the tool itself failed"
export const EXIT_CODE_STALE = 1;
export const EXIT_CODE_ERROR = 2;

// First line of every generated file; pack writes its own entry file with it
export const FILE_HEADER_LINE = `/* ${GENERATED_MARKER}. Do not edit. */`;

export const PACK_STAGING_PREFIX = '.strapi-schemas-pack-src-';
